In [1]:
l1=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
print(l1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [5]:
print("first ele = ",l1[0])
print("middle element = ",l1[int(len(l1)/2)-1])
print("last ele = ",l1[19])

first ele =  1
middle element =  10
last ele =  20


In [10]:
print("first five elements = ",l1[:5])
print("last five elements = ",l1[15:])
print("list of 5 to 15 ele = ",l1[4:14])

first five elements =  [1, 2, 3, 4, 5]
last five elements =  [16, 17, 18, 19, 20]
list of 5 to 15 ele =  [5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [13]:
#list comprehension
square_nos=[x**2 for x in l1 if x <= 10]
print(square_nos)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [17]:
#filter list
even_nos=[x for x in l1 if x%2 == 0]
print(even_nos)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [20]:
import random
l2=random.sample(range(1,100),k=10)



In [25]:
print(l2)
l2.sort()
print(l2)
l2.sort(reverse=True)
print(l2)

[4, 42, 43, 56, 77, 81, 83, 86, 90, 93]
[4, 42, 43, 56, 77, 81, 83, 86, 90, 93]
[93, 90, 86, 83, 81, 77, 56, 43, 42, 4]


In [26]:
l3=[[1,2,3],
    [4,5,6],
    [7,8,9]]

print(l3[1][2])

6


In [31]:
l4=[{"name":"Pinal","score":91},{"name":"ruchit","score":92}]
l4.sort(key=lambda l4:l4['score'],reverse=True)
print(l4)

[{'name': 'ruchit', 'score': 92}, {'name': 'Pinal', 'score': 91}]


In [33]:
#def transpose(l3):
print(l3)
for i in l3:
    print(i)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [53]:
row=len(l3)
col=len(l3[0])
import numpy as np

l4=np.zeros((row,col),dtype=int)



In [54]:
j=0
i=0
while i<row:
    j=0
    while j<col:
        l4[j][i]=l3[i][j]
        j+=1
    i+=1

print(l4)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [59]:
l5=[item for sublist in l3 for item in sublist]
print(l5)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [61]:
temp_l1=[1,2,3,4,5]
temp_l2=[6,7,8,9,10]
res=list(zip(temp_l1,temp_l2))
print(res)

[(1, 6), (2, 7), (3, 8), (4, 9), (5, 10)]


In [65]:
#list_intersection
ll1=[12,34,56,11,3,2]
ll2=[12,34,67,21,67,21]

ll3=[x for x in ll1 if x in ll2]



In [66]:
print(ll3)


[12, 34]
