In [2]:
import numpy as np
'''1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.'''
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[2,3,4,5,16],[6,34,12,45,22],[5,6,2,8,9]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 2,  3,  4,  5, 16],
       [ 6, 34, 12, 45, 22],
       [ 5,  6,  2,  8,  9]])

In [3]:
arr.shape

(5, 5)

In [4]:
for i in range(0,5):
    arr[i][2]=1

In [5]:
arr

array([[ 1,  2,  1,  4,  5],
       [ 6,  7,  1,  9, 10],
       [ 2,  3,  1,  5, 16],
       [ 6, 34,  1, 45, 22],
       [ 5,  6,  1,  8,  9]])

In [6]:
'''2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.'''
for i in range (0,5):
    arr[i][i]=0
print(arr)

#or it can be done with help of diagonal

np.fill_diagonal(arr,777)
print(arr)

[[ 0  2  1  4  5]
 [ 6  0  1  9 10]
 [ 2  3  0  5 16]
 [ 6 34  1  0 22]
 [ 5  6  1  8  0]]
[[777   2   1   4   5]
 [  6 777   1   9  10]
 [  2   3 777   5  16]
 [  6  34   1 777  22]
 [  5   6   1   8 777]]


In [7]:
'''1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.'''
arr2=np.empty((6,6),dtype=int)
import random
for i in range(0,6):
    for j in range (0,6):
        arr2[i][j]=int(random.randint(1,36))
print(arr2)
sub_array=arr2[2:5,1:4]
print("sub array")
print(sub_array)


[[29  4  1 13  9  6]
 [15 14 18 21 24  4]
 [35 22  8 26 23  6]
 [29  4 15 36 33  1]
 [ 5 28 20  6 33 20]
 [32 24  9 36  3 23]]
sub array
[[22  8 26]
 [ 4 15 36]
 [28 20  6]]


In [8]:
#one way
border_elements = np.concatenate((arr2[0, :], arr2[-1, :], arr2[1:-1, 0], arr2[1:-1, -1]))
#border_elements
#other way
print(arr2[0, :])
print(arr2[: ,0])
print(arr2[5,:])
print(arr2[:, 5])

[29  4  1 13  9  6]
[29 15 35 29  5 32]
[32 24  9 36  3 23]
[ 6  4  6  1 20 23]


In [9]:
'''1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.'''

a1=np.random.randint(1,21,size=(3,4))
print(a1)
a2=np.random.randint(1,31,size=(3,4))
print(a2)

#

[[ 3 12 20 14]
 [19  8  6  7]
 [19  3 12  3]]
[[27 12  9  7]
 [10 28  8  4]
 [ 5 27 16  5]]


In [10]:
addition=a1+a2
print(addition)
sub=a2-a1
print(sub)
div=a2/a1
print(div)
mul=a1*a2
print(mul)

[[30 24 29 21]
 [29 36 14 11]
 [24 30 28  8]]
[[ 24   0 -11  -7]
 [ -9  20   2  -3]
 [-14  24   4   2]]
[[9.         1.         0.45       0.5       ]
 [0.52631579 3.5        1.33333333 0.57142857]
 [0.26315789 9.         1.33333333 1.66666667]]
[[ 81 144 180  98]
 [190 224  48  28]
 [ 95  81 192  15]]


In [11]:
'''Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.'''

a3=np.arange(0,16).reshape((4,4))
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
#column wise sum
c=np.sum(a3,axis=0,dtype=int)
print("column sum = ",c)
r=np.sum(a3,axis=1,dtype=int)
print("row sum = ",r)



column sum =  [24 28 32 36]
row sum =  [ 6 22 38 54]


In [13]:
'''1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.'''

a4=np.random.randint(1,100,size=(5,5))
print(a4)

print("mean  = ",np.mean(a4))
print("median = ",np.median(a4))
print("stand deviation = ",np.std(a4))
print("variance = ",np.var(a4))


[[45 64 33 84 90]
 [76 79 34 59 54]
 [76 72 77 70 47]
 [60 25  3 44 85]
 [ 3 60 46 48 66]]
mean  =  56.0
median =  60.0
stand deviation =  23.077261535979524
variance =  532.56


In [14]:
'''2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).'''

#data normalization

a5=np.random.randint(1,10,size=(3,3))
print("mean = ",np.mean(a5))
print("sd = ",np.std(a5))
#normalization=(data - mean)/std_dev
normalized_array=a5-np.mean(a5)/np.std(a5)
print("after normalization array = ")
print(normalized_array)
print("after mean =",np.mean(normalized_array))
print("after std = ",np.std(normalized_array))



mean =  5.333333333333333
sd =  2.6666666666666665
after normalization array = 
[[ 6.  1.  0.]
 [ 6.  4.  4.]
 [ 3.  7. -1.]]
after mean = 3.3333333333333335
after std =  2.6666666666666665


In [15]:
'''1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.'''

a6=np.random.randint(1,100,size=(3,3))
print("before = ",a6)
sample_add=[12,12,12]
print("after = ",a6+sample_add)
sample_sub=[20,20,20]
print("after sub= ",a6-sample_sub)


before =  [[28 43 95]
 [23 99 89]
 [31 83 93]]
after =  [[ 40  55 107]
 [ 35 111 101]
 [ 43  95 105]]
after sub=  [[ 8 23 75]
 [ 3 79 69]
 [11 63 73]]


In [17]:
'''1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.'''
print(a6)
print("determinant = ",np.linalg.det(a6))

#since det != 0 hence proceed with iverse
print("inverse. = ",np.linalg.inv(a6))

#check if it returns back to oiginal space if we get indentity matrix back
print("a6 @ a6_inv =\n ",a6 @ np.linalg.inv(a6))

#here note diaglonal must be 1 then it is identity matrix, ignore others
#check if it identity matrix

print("identity matrix verification = ",np.allclose(a6 @ np.linalg.inv(a6), np.eye(3)))

eigvalues,eigvector=np.linalg.eig(a6)

print("Eigne Value = ",eigvalues)
print("Eigen Vector = ")
print(eigvector)


[[28 43 95]
 [23 99 89]
 [31 83 93]]
determinant =  -32579.99999999998
inverse. =  [[-0.05586249 -0.11927563  0.17120933]
 [-0.01903008  0.01046654  0.00942296]
 [ 0.03560467  0.03041743 -0.05472683]]
a6 @ a6_inv =
  [[ 1.00000000e+00 -2.46330734e-16  3.74700271e-16]
 [ 2.56739074e-16  1.00000000e+00 -4.16333634e-17]
 [ 0.00000000e+00  1.11022302e-16  1.00000000e+00]]
identity matrix verification =  True
Eigne Value =  [203.15379158  -6.78609693  23.63230535]
Eigen Vector = 
[[-0.48456173 -0.90968179  0.86722205]
 [-0.62765584 -0.13317192 -0.46738725]
 [-0.6093013   0.39337549  0.17168306]]


In [20]:
'''2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.'''

a7=np.random.randint(1,100,size=(2,3))
a7


array([[54, 49, 30],
       [20, 88, 21]])

In [21]:
a8=np.random.randint(1,100,size=(3,2))
a8

array([[18, 52],
       [30, 91],
       [17, 62]])

In [24]:
#this can achieved by dot product
print(a7.dot(a8))

[[ 2952  9127]
 [ 3357 10350]]


In [32]:
'''### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).'''
a9=np.arange(1,10).reshape(3,3)
a9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
reshape1=a9.reshape(1,9)
reshape1

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
reshape2=reshape1.reshape(9,1)
reshape2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [36]:
print(a9)
print(a9.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
'''### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.'''