In [3]:
import numpy as np

In [6]:
#creating 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
#reshape
arr1=arr1.reshape(1,5)
arr1

array([[1, 2, 3, 4, 5]])

In [11]:
arr2=np.array([[1,2,3,4,5],[5,6,7,8,9]])
arr2

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [12]:
arr2.shape

(2, 5)

In [ ]:
#arange 
#start,stop & step
np.arange(0,11,2).reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
arr5=np.eye(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
#attributes of array
arr=np.array([[1,2,3],[4,5,6]])
print("shape = ",arr.shape)
print("no of dimensions = ",arr.ndim)
print("no of elements ",arr.size)
print("data type of array = ",arr.dtype)
print("memory used by array in bytes = ",arr.itemsize)

shape =  (2, 3)
no of dimensions =  2
no of elements  6
data type of array =  int64
memory used by array in bytes =  8


In [28]:
#array vectorized operations, element to elemnt operation & return will be array as well
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("Addition = ",arr1+arr2)
print("Substraction = ",arr2-arr1)
print("Multiplication = ",arr1*arr2)
print("division = ",arr2/arr1)

Addition =  [ 7  9 11 13 15]
Substraction =  [5 5 5 5 5]
Multiplication =  [ 6 14 24 36 50]
division =  [6.         3.5        2.66666667 2.25       2.        ]


In [31]:
#universal function - applies to all elemnts if array
print("square root = ",np.sqrt(arr1))
print("exponentinal = ",np.exp(arr1))
print("sine = ",np.sin(arr1))
print("natural log = ",np.log(arr1))


square root =  [1.         1.41421356 1.73205081 2.         2.23606798]
exponentinal =  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
sine =  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
natural log =  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [32]:
#array slicing and indexing
arr3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
print(arr3[0][0])
print(arr3[1:,2:])


1
[[ 7  8]
 [11 12]]


In [34]:
#modify array elemts
arr3[0][0]=100
arr3

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [38]:
#statistical concept - normalization
#normalization is nothing but mean of data should be 0 and standard deviation should be 1
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)
print("mean = ",mean," standard deviation = ",std_dev)
#normalize data
normalized_data=(data-mean)/std_dev
print(normalized_data)
print("mean of normalized data = ",np.mean(normalized_data)," and std_dev = ",np.std(normalized_data))

mean =  3.0  standard deviation =  1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
mean of normalized data =  0.0  and std_dev =  0.9999999999999999


In [39]:
#other stats operation
median=np.median(data)
print("median = ",median)
variance=np.var(data)
print("variance = ",variance)

median =  3.0
variance =  2.0


In [40]:
#logical operations
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
#retrive elements
data[data>5]

array([ 6,  7,  8,  9, 10])

In [43]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])